# Generated by Django 4.2.25 on 2025-10-04 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_ad_adcampaign_subscriptionplan_usersubscription_tip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adview',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='adview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='adview',
            name='video',
        ),
        migrations.RemoveField(
            model_name='creatorearnings',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='user',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='video',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='video',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='videoad',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='videoad',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='videoad',
            name='video',
        ),
        migrations.DeleteModel(
            name='Ad',
        ),
        migrations.DeleteModel(
            name='AdCampaign',
        ),
        migrations.DeleteModel(
            name='AdView',
        ),
        migrations.DeleteModel(
            name='CreatorEarnings',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Revenue',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.DeleteModel(
            name='Tip',
        ),
        migrations.DeleteModel(
            name='UserSubscription',
        ),
        migrations.DeleteModel(
            name='VideoAd',
        ),
    ]
